### ISSUE TITLE
2da_practica_Visual_Studio

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-tec-design#1]
Integrantes del equipo: 
Daisy Gonzalez Lita
Maribel Santiago Bautista 
[Documentación_ Visual_Studio_Daisy_Maribel.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-tec-design/files/14276274/Documentacion_.Visual_Studio_Daisy_Maribel.pdf)

https://drive.google.com/file/d/1JNERYlUaq44XezbN9k2LB-iuIglA2zaQ/view?usp=sharing
El link de la carpeta donde se encuentra el proyecto.

**Comment by marxgonzalez29** [comment]
100/100
Es legible las palabras que se tratan de dar a entender, aparte tiene una buena presentación, es un buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
